### ISSUE TITLE
Wrong title in award preview

### ISSUE THREAD

**Issue by Kasperice** [coders-school/site#102] opened 2020-07-17 17:23 UTC
![image](https://user-images.githubusercontent.com/26752357/87813828-e86c8e00-c862-11ea-806b-173e6019fd8f.png)

There is "Latest Blog" instead of better name

**Comment by Kasperice** [comment] 2020-07-17 17:23
Same issue is visible when you go to "Osiagniecia" and select one

**Comment by kawapa** [comment] 2020-07-19 11:16
Duplicate of [#50](https://github.com/coders-school/site/issues/50)

Long story short: this is not something that we can fix easily, therefore we postponed it to the end of the course.

**Closed by kawapa** 2020-07-19 11:16 UTC
Labels: Low Priority, On Hold
