### ISSUE TITLE
No visualisation of progress on modules screen

### ISSUE THREAD

**Issue by adamvm** [coders-school/site#85] opened 2020-06-13 03:47 UTC
On main screen for modules there is no visibility for progress which moule is done, which is in the middle. I need to go inside and check if I do not remember what I left for later execution

![image](https://user-images.githubusercontent.com/5563693/84559243-33155a80-ad39-11ea-868d-ae16a8efcba7.png)

It would be greate if we can add smaller version of this progress bar for every module

![image](https://user-images.githubusercontent.com/5563693/84559264-59d39100-ad39-11ea-8bd3-9af1dcdee720.png)

**Comment by kawapa** [comment] 2020-06-16 19:05
Duplicate of [Issue 81](https://github.com/coders-school/site/issues/81)

**Closed by kawapa** 2020-06-16 19:05 UTC
