### ISSUE TITLE
STL#3 Pictures are not working in course platform

### ISSUE THREAD

**Issue by jakjan95** [coders-school/site#105] opened 2020-08-29 08:44 UTC
No photos on the course, tested on linux / windows.
As show below:
![image](https://user-images.githubusercontent.com/57813618/91632886-4d7bdd80-e9e4-11ea-83b3-d93bcfb533e7.png)

**Comment by kawapa** [comment] 2020-09-01 07:39
The images are not displayed in lessons because the Learning Platform does not accept relative links to files/images/etc. At the moment we don't want to change it to preserve the portability of the repository (if we were to move it somewhere else, it would corrupt the appearance on GH).

Duplicate of [#78](https://github.com/coders-school/site/issues/78)

**Closed by kawapa** 2020-09-01 07:39 UTC
